name: Build KiraHack

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: macOS

    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Geode Mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: latest

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: KiraHack-${{ matrix.name }}
          path: ${{ steps.build.outputs.build-output }}
